name: Download Excel Report

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  download_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Verify repository structure
        run: |
          echo "Verifying repository structure..."
          ls -R

      - name: Run download script
        env:
          API_TOKEN: ${{ secrets.FRONT_API_TOKEN }}
        run: |
          mkdir -p reports
          python /FrontExcel/FrontDL.py

      - name: List files in reports directory
        run: ls -l reports

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add reports/*
          git commit -m 'Add downloaded Excel report' || echo "No changes to commit"
          git push
