name: Lumen Report

on:
  schedule:
    - cron: '15 18 * * *' # 6:15 PM UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Check Python version
        run: python --version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: List installed packages
        run: pip list

      - name: Create Reports directory
        run: mkdir -p Lumen/Reports

      - name: Run Script
        run: python Front\ XLSX\ Download.py
        working-directory: FrontXLSX

      - name: List files in reports directory
        run: ls -l Lumen/Reports

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add Lumen/Reports/*
          git commit -m 'Add downloaded Excel report' || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/JustinH144/FrontExcel.git HEAD:main
