name: Scheduled Commit and Push Changes

on:
  schedule:
    - cron: '30 8 * * *'

permissions:
  contents: write

jobs:
  push-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Commit and push changes
        env:
          GH_PAT: ${{secrets.GH_PAT}}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add Reports/*
          git commit -m 'Add downloaded Excel report' || echo "No changes to commit"
          git push https://x-access-token:${{secrets.GH_PAT}}@github.com/JustinH144/FrontExcel.git HEAD:main
